[package]
name = "art"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.25.1"
indexmap = "2.2.6"
itertools = "0.12.1"
log = "0.4.21"
pretty_env_logger = "0.5.0"
rand = "0.8.5"
